name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Pull dependencies
      run: |
        cd ./android/app/src/main/cpp/
        git clone https://github.com/krrishnarraj/libopencl-stub.git
    - name: Grant execute permission for gradlew
      run: chmod +x ./android/gradlew
    - name: Build with Gradle
      run: |
        cd ./android
        ./gradlew build
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: Android-latest
        path: ./
